[project]
name = "nces-ipeds-archive"
version = "1.0.0"
description = "Tools to download NCES IPEDS data"
readme = "readme.md"
requires-python = ">=3.9"
dependencies = [
    "filetype>=1.2.0",
    "setuptools>=76.0.0",
]
